[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GenericFFT = "a8297547-1b15-4a5a-a998-a2ac5f1cef28"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
