[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"
TravellingSailorProblem = "a3415216-7039-422d-b654-bd7aa2f43b3e"